name: Deploy HTML Website to Linux Server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy website files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          source: "."
          target: "/home/${{ secrets.SERVER_USER }}/Documents/website"

      - name: Setup Nginx on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            USER=${{ secrets.SERVER_USER }}
            PASS=${{ secrets.SERVER_PASS }}

            echo "$PASS" | sudo -S apt update
            echo "$PASS" | sudo -S apt install -y nginx

            echo "$PASS" | sudo -S bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /home/$USER/Documents/website;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'

            echo "$PASS" | sudo -S chmod -R 755 /home/$USER/Documents/website
            echo "$PASS" | sudo -S nginx -t
            echo "$PASS" | sudo -S systemctl reload nginx
